### ISSUE TITLE
Add test for cell_set_preferred_alias uniqueness

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#100]
cell_set_preferred_alias should be unique within any one dendrogram  - ignoring nodes with no cell_set_preferred_alias, no two nodes should have the same one.  This check should run automatically on all dendrogram files on the repo.

**Comment by hkir-dev** [comment]
A github action created for this purpose: https://github.com/obophenotype/brain_data_standards_ontologies/actions/workflows/dendrogram_check.yaml

Action is disabled since it fails due to following issues:
- cell_set_preferred_alias 'L5 IT_2' is duplicate in CCN202002013
- cell_set_preferred_alias 'Meis2' is duplicate in CCN202002013
- cell_set_preferred_alias 'L6' is duplicate in CCN201908210

Related pull request created: https://github.com/obophenotype/brain_data_standards_ontologies/pull/150
