### ISSUE TITLE
L5 T Martinotti difficulties 

### ISSUE THREAD

**Issue by shawntanzk** [obophenotype/brain_data_standards_ontologies#129]
![Screenshot 2021-06-24 at 13.22.16.png](https://images.zenhubusercontent.com/60ae6c7d916945778aa3f3c2/0697e07d-7a2d-448e-bc49-f9893d028575)

![Screenshot 2021-06-24 at 13.23.26.png](https://images.zenhubusercontent.com/60ae6c7d916945778aa3f3c2/946d6962-e607-4d23-9586-6dd5b8bcb960)

Currently L5 T Martinotti cell is not greatly represented in the ontology -> it probably has to do with the node CS202002013_159 does not have Myh8_1-3 under it (guessing from the two screenshots above) - perhaps because there is a node in the middle that does not fit? Wonder if this was the case @jeremymiller? 

Given how this is not a HUGE problem, perhaps we can handle this after workshop which should be priority now. (I've placed it under first post workshop release)

**Comment by jeremymiller** [comment]
The distribution of cells collected for patch-seq depend on a number of biological (e.g., rarity of the cells themselves) and technical (e.g., how easy it is to find and patch cells without killing them) parameters.  I'm surprised you only found one cell type with an issue like this.  Based on how the analysis was done, I don't think it is likely due to details of the dendrogram/ontology.

**Comment by shawntanzk** [comment]
Was just revising this problem - realised that 'L5 T Martinotti cell' is a pref label that labels RNAseq 034-035 which is technically wrong. The correct grouping is already there as seen in the picture above, was hence wondering if we can just delete the pref label for CS202002013_159? @jeremymiller

**Comment by shawntanzk** [comment]
ok, new version just got updated and I notice now that the Myh8 aren't under L5 T Martinotti, is this correct @jeremymiller? 
![Screenshot 2021-08-16 at 15 44 42](https://user-images.githubusercontent.com/76212760/129582624-5d4cbe2c-6438-4711-830a-59e5f06f5303.png)

**Comment by jeremymiller** [comment]
It turns out there are two L5 T Martinotti cell groups, which I didn't realize before:
![image](https://user-images.githubusercontent.com/25486679/129593034-7c5f7128-20db-4eae-846f-1fcadd4c6657.png)
Here are all the Martinotti cell type:
![image](https://user-images.githubusercontent.com/25486679/129593107-c9b1e0da-14a0-42f5-bcec-e7553ec8419e.png)
I think a good solution would be to add RNAseq 034-035 to CS202002013_256 and then remove the annotation and preferred alias from CS202002013_159, essentially combining these two groups into one.

**Comment by shawntanzk** [comment]
Should be fixed with https://github.com/obophenotype/brain_data_standards_ontologies/commit/d31242fdd446f188bcf524ec2be4a168ac8817fc 
Will wait for ontology refresh and close if fix works

**Comment by shawntanzk** [comment]
Fixed
