### ISSUE TITLE
On all class templates - only make entries for the descendants or root nodes (excluding root nodes themselves)

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#50]
_class.tsv
_equivalent_markers.tsv
patterns/data/brainCellRegionMarker.tsv

**Comment by hkir-dev** [comment]
update completes, please see the related [file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_denormalised_markers/src/templates/CCN202002013_class.tsv)
but with this change, we are not able to generate class files for CCN201810310 CCN201908211 CCN201908210 taxonomies since we don't have config for them

**Comment by hkir-dev** [comment]
Merged Shawn's edits to the [file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_denormalised_markers/src/templates/CCN202002013_class.tsv) again, checking it again can be good.

**Comment by hkir-dev** [comment]
In the [config](https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_denormalised_markers/src/dendrograms/taxonomy_details.yaml) CS202002013_103, CS202002013_111, CS202002013_112 and CS202002013_113 are defined as root node and in the [dendrogram](https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_denormalised_markers/src/test/test_data/CCN202002013.png) they are leaf at the same time. 
With this change defining these in the config will have no effect.

**Comment by dosumis** [comment]
It looks like root nodes are still getting through (I may not have been entirely consistent on this).

Looking at the product I think it's best to exclude, e.g. [AllenDendClass_CS202002013_123](http://ec2-18-188-87-230.us-east-2.compute.amazonaws.com:8080/ontologies/bds/terms?iri=http%3A%2F%2Fwww.semanticweb.org%2Fbrain_data_standards%2FAllenDendClass_CS202002013_123&viewMode=PreferredRoots&siblings=false) groups all GABAergic interneurons of the 'primary motor cortex'.  This makes for a confusing parallel grouping to the ones Shawn has worked on.

**Comment by hkir-dev** [comment]
Run a clean build, now in the [bdsscratch-full.owl](https://raw.githubusercontent.com/obophenotype/brain_data_standards_ontologies/fix_issue50/bdscratch-full.owl) root nodes not exist.
Intermediate files (all_templates.owl, components/%_class.owl, components/%_equivalent_class.owl) caused the issue I think. Should we delete them after the completion of the pipeline? Otherwise, they are acting like caches of previous builds.

**Comment by dosumis** [comment]
> Intermediate files (all_templates.owl, components/%_class.owl, components/%_equivalent_class.owl) caused the issue I think. Should we delete them after the completion (or at the begining) of the pipeline? Otherwise, they are acting like caches of the previous builds.

We need to keep components/all_templates.owl as directly imported to editors file.  OK to delete other components (although sometimes useful for debugging).  To run cleanly,  it might be useful to use `touch` to fool `Make` into registering all source files as changed.
