### ISSUE TITLE
Re-run RF maker prediction for *all* nodes in 202002013

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#55]
Currently we only have markers for nodes names in an earlier version of the dendrogram.

**Comment by dosumis** [comment]
Hi @BAevermann  - any progress on this?

**Comment by BAevermann** [comment]
I am working on it. Taking the longer road. Instead of manually generating the necessary labels, I am writing code so that we can more easily pipeline it in the near future. 

One issue is that we should request that the Allen release a cell to leaf node accession # mapping. As far as I know, the cells are still mapped to the preferred labels (however they update their website regularly...)

**Comment by dosumis** [comment]
> I am working on it. Taking the longer road. Instead of manually generating the necessary labels, I am writing code so that we can more easily pipeline it in the near future.

Not sure I follow.  We have label generation code for the ontology and the dendrograms and your lookup for gene IDs -> labels.

> One issue is that we should request that the Allen release a cell to leaf node accession # mapping. As far as I know, the cells are still mapped to the preferred labels (however they update their website regularly...)

Did you ask @jeremymiller  - bit shocking we're not running everything on accessions already.  I really think labels are unsafe.  

I think this is part of a more general problem with standardising pipelines - where data comes from and in what form.  Would be good to have a dedicated call/hackathon on this - maybe towards the end of next month?

**Comment by jeremymiller** [comment]
We (by which I mean the technology and project teams at the Allen Institute) are working on implementing a taxonomy service which would allow scientists to run a clustering on a specific set of cells and tag this specific instance of the cells in the database (e.g., versioned data set) to specific instance of a taxonomy so it can be tracked and reproduced.  At best it will be a few months before something like this is available (plus convincing scientists to use it) and so for now we just need to be careful with tracking these kinds of things.  I do like the idea of a dedicated call/hackathon for how to deal with versions in the near term.  All this being said, I'm not sure I understand the specific issue right now.  Maybe we can discuss briefly at the ontology meeting Monday?

**Comment by dosumis** [comment]
Specific, urgent issue:  @BAevermann would like cell_set_accession to cell mapping for his analysis as he is relying on mappings to potentially unstable/outdated node labels (cell_set_preferred_alias?) right now.   Would you be able to provide these to him for mouse MOP (also needed for other primary motor cortex dendrograms)?   Presumably we know what data each of these corresponds to.  

Re general call - Let's aim for end April (Monday is a holiday here so I may cancel call).

**Comment by dosumis** [comment]
@BAevermann - any progress?  Do the files @jeremymiller provided give you what you need?

**Comment by BAevermann** [comment]
Hey David!

The next level up from leaf is currently running (so another ~50 nodes worth). That should be done this week. I am still working on updating the code to make the process automated.

The files had the updated label to leaf nodeID mapping, but not leaf nodeID mapping to cells. So that probably needs to be added to Allen’s outputs if using the dendrogram is to become the standard by which to handle these taxonomies….

b.

From: David Osumi-Sutherland ***@***.***>
Date: Wednesday, April 7, 2021 at 7:47 AM
To: obophenotype/brain_data_standards_ontologies ***@***.***>
Cc: Aevermann, Brian ***@***.***>, Mention ***@***.***>
Subject: Re: [obophenotype/brain_data_standards_ontologies] Re-run RF maker prediction for *all* nodes in 202002013 (#55)

@BAevermann<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FBAevermann&data=04%7C01%7Cbaeverma%40jcvi.org%7C04d6b0974183448a8e4e08d8f9d413a4%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637534036562662106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bgX9UYkVKvWSGmlUUsZRcovpdneeITUUlgjCxPCBOqA%3D&reserved=0> - any progress? Do the files @jeremymiller<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeremymiller&data=04%7C01%7Cbaeverma%40jcvi.org%7C04d6b0974183448a8e4e08d8f9d413a4%7C24d967f13ed84448baa6560ec572acb3%7C0%7C0%7C637534036562672100%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YIEY4SYmY2YFzU7IT5hKqCKN7xu5giAdKlzeJpkHsC8%3D&reserved=0> provided give you what you need?

**Comment by BAevermann** [comment]
Added file to the markers folder containing almost all of the nodes (probably all the necessary nodes)

**Comment by dosumis** [comment]
> Added file to the markers folder containing almost all of the nodes (probably all the necessary nodes)

Awesome. Please check QC report (if you haven't already) @hkir-dev can help point you to it & discuss any issues

@hkir-dev  - if no major issues can you try running a build?
