### ISSUE TITLE
Fix missing nodes/mappings in ec_individuals build

### ISSUE THREAD

**Issue by dosumis** [obophenotype/brain_data_standards_ontologies#67]
1. In some cases we have no cell_set_preferred_alias

e.g. 

cell_set_preferred_alias | original_label | cell_set_label | cell_set_accession | cell_set_aligned_alias | cell_set_additional_alias | cell_set_alias_assignee | cell_set_alias_citation | cell_set_structure | cell_set_ontology_tag | taxonomy_id | species | modality | child_cell_set_accessions
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
 Lamp5 Pax6 | Lamp5 Pax6 | RNAseq 001 | CS202002013_1 |   | Lamp5_4
. | n14 | RNAseq 005-007 | CS202002013_130 |   | Neurogliaform cell

Decision: Create a report to request cell_set_preferred alias added in cases like this (ditto for if there is no cell_set_preferred_alias but there is a cell_set_additional_alias).  @jeremymiller @hkir-dev will generate report.

2. Terms that are both leaf and root should be added - example pericyte _112

**Comment by hkir-dev** [comment]
List of nodes that don't have  cell_set_preferred_alias but has cell_set_additional_alias are:
ID | cell_set_additional_alias
-- | --
CS202002013_130 | Neurogliaform cell	
CS202002013_139 | L5/6 CCK cell	
CS202002013_143 | L5 VIP cell	
CS202002013_159 | L5 T Martinotti cell	
CS202002013_161 | L5 non-Martinotti cell	
CS202002013_164 | L2/3/5 fan Martinotti cell	
CS202002013_165 | L5/6 non-Martinotti cell	
CS202002013_170 | L6 Th+ SST/PV cell	
CS202002013_177 | Upper FS Basket cell	

@jeremymiller for your review

**Comment by jeremymiller** [comment]
Some of the nodes of the tree don't have preferred aliases because they are internal nodes where we haven't characterized them based on transcriptomics.  I think if there is a node with an additional alias but no preferred alias then it is probably okay to use that label.  The one major caveat is that these additional aliases are all based on morphology and electrophysiology, however (1) the other preferred aliases are based on transcriptomics and other features and (2) this is only a small subset of the nodes with additional aliases based on morphology and electrophysiology.  Another option would be to use a term like "VIP subset 143" for "CS202002013_143" which indicates that it is some VIP subset and links to the ID, or something like that.

**Comment by dosumis** [comment]
Decision:  We will add a processing after loading the dendrogram, that copies the first cell_set_additional_alias across cell_set_preferred_alias if no cell_set_preferred_alias is present.  This is a hack for the pipeline to ensure that classes are generated for all such terms and that they get names.

**Comment by hkir-dev** [comment]
> Decision: We will add a processing after loading the dendrogram, that copies the first cell_set_additional_alias across cell_set_preferred_alias if no cell_set_preferred_alias is present. This is a hack for the pipeline to ensure that classes are generated for all such terms and that they get names.

We had already implemented and merged to master, but observed a bug while checking the code. We may close this issue with the related bug fix: https://github.com/obophenotype/brain_data_standards_ontologies/pull/117

> Terms that are both leaf and root should be added - example pericyte _112

Control added: https://github.com/obophenotype/brain_data_standards_ontologies/blob/73dfbc088e413ab372c8582aa5754361b9e9b30f/src/scripts/template_generation_utils.py#L157

**Comment by dosumis** [comment]
We are now using cell_set_additional_alias[0]
